### ISSUE TITLE
Web + Android

### ISSUE THREAD

**Issue by johndangerstorey** [mcnamee/react-native-starter-app#10]
Are you planning on adding webpack and android support?  Right now this is only for iOS and I was looking around at some other projects and this one is sooooo close to what I want, just lacking examples for implementing this on android and web.  If it's not in the roadmap for you I might take this on for you... but wanted to check on your thoughts first.  It'd probably borrow from the architecture in this project: https://github.com/benoitvallon/react-native-nw-react-calculator

**Comment by mcnamee** [comment]
Hey @johndangerstorey 
It'd definitely be awesome to have all of the features you mentioned!

@wireblue is currently working on refactoring the project so that it uses Redux - we're hoping it'll be done in about 2-4 weeks.

I'd struggle to find time at the moment for the Android/Web/Desktop output - but if you have a chance to work on it, submit a pull request 👍

**Comment by empitechathu** [comment]
Hey mate I really love the work you have done .. I managed to work your code in android app too .. But I dont know if its correct way to do it. But its working for me .. I hope you know the globalizing the main.js class and inherit that from index.ios.js and index.android.js files. Thats how I did it . :)

**Comment by mcnamee** [comment]
Hey @empitechathu - awesome man. Submit a pull request and I'll check it out

**Comment by mcnamee** [comment]
Hi @johndangerstorey and @empitechathu 
This project is now Android and Redux ready! Give it a go and let me know if you have any issues
