### ISSUE TITLE
'react-native-device-info' lib included in project, but not used. 

### ISSUE THREAD

**Issue by shic** [mcnamee/react-native-starter-app#111]
If someone tell me where to put this infomation. I can do it, and contribute to this project

**Comment by mcnamee** [comment]
Good point. I've kept it in because I use it on the majority of my personal projects for things like debugging (eg. Displaying app info in app or auto submitting device/ app info when users submit bug/feedback from within the app).

Feel free to submit a pull request to remove it (I.e. should be as simple as removing from package.json) otherwise when I get a spare moment, I might make use of the module somewhere in the project.
