### ISSUE TITLE
'setBackgroundColor' is only available on Android

### ISSUE THREAD

**Issue by lockeyo** [mcnamee/react-native-starter-app#38]
There is no background on the first screen on iOS. 

The following error shows up: 
`'setBackgroundColor' is only available on Android`

How can I fix this problem to show a proper background? In advance, thank you for sharing the code. I really like your project.

**Comment by mcnamee** [comment]
Hi @lockeyo 
That warning is coming from [here](https://github.com/mcnamee/react-native-starter-app/blob/master/ReactApp/containers/app.js#L50).

I believe it's just that the `setBackgroundColor` method only applies to Android, so it's just a warning for iOS, so that the developer is aware.

If the warning is causing some frustration, you could probably wrap that method call in a Platform conditional, so that it's only called on Android devices.

**Comment by sfarazkhan** [comment]
This warning appears when you use setBackgroundColor property with StatusBar inside the render.
StatusBar.setBackgroundColor('transparent', true);

It works fine on android but it will show warning on iOS. Add a Platform check on it, this warning will be removed.
