### ISSUE TITLE
navigation performance is too bad. can you fix it?

### ISSUE THREAD

**Issue by jiqimaogou** [mcnamee/react-native-starter-app#58]

**Comment by Jean-PierreGassin** [comment]
@jiqimaogou could you please elaborate on what your issue is? Usually when the simulator is slow (which I assume is what you're referring to) it means that you're in debug mode and your developer console isn't the focused tab of Google Chrome.

For reference, below are some other issues which may be related, I suggest you have a read in case it fixes your problem.

[Issue #55](https://github.com/mcnamee/react-native-starter-app/issues/55)
[Issue #44](https://github.com/mcnamee/react-native-starter-app/issues/44)

**Comment by csumrell** [comment]
I see the same thing. Switching between tabs often seems laggy and takes a bit of time to actually switch. The slider tabs at the top also seem to lag behind in animation when swiping between the them. I am testing on an actual Samsung S7 edge

**Comment by mcnamee** [comment]
@csumerell - are testing the app in release mode on your device as suggested in issue #55 ?
