### ISSUE TITLE
First run errors

### ISSUE THREAD

**Issue by nloui** [mcnamee/react-native-starter-app#70]
Hi there! I'm having some trouble getting the app to run.  

I've pulled the repo, ran npm install, then opened the SDK but no go :-(.  Getting a series of these errors followed by process terminated.  Running the latest version of react native.

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap

**Comment by tugal** [comment]
Same issue here

**Comment by DavidLi-Minxiao** [comment]
I had the same issue here.

I believe it's a npm package that's upgraded breaking the application. 

I went into package.json and removed all the variable version references, and `npm install`ed again - worked perfectly.

If you're just that 15 seconds lazier(*ahem*, more efficient - probably not actually faster), [here's my `yarn.lock`]http://www.filedropper.com/yarn).

**Comment by sortinousn** [comment]
This seems to be happening to every react-native app that I run, at first I thought it might have been my global packages causing the issue but after completely wiping my node-modules and trying on three different workstations I've come to the conclusion that it has to be some common dependency. I've read that it may be because of an update to react-native-router-flux v3.38.1, rolling back to the previous version  may fix the issue.

**Comment by Jean-PierreGassin** [comment]
Hey @nloui, 

Are you able to provide an example of the errors that you're getting? Perhaps I can try to reproduce and debug the issue.

**Comment by mcnamee** [comment]
Hey @nloui @tugal @sortinousn 
It was to do with react-native-router-flux - I've updated package.json in master, which resolves the issue.

Please let me know if the issue persists
