### ISSUE TITLE
JWT Re-authorisation failing

### ISSUE THREAD

**Issue by Jean-PierreGassin** [mcnamee/react-native-starter-app#71]
Hey @mcnamee,

I've just come across a bug [in the JWT getStoredCredentials method](https://github.com/mcnamee/react-native-starter-app/blob/master/src/lib/api.jwt.js#L81).

Currently when you try to retrieve stored credentials via AsyncStorage the __storedCredsStr__ variable is never replaced with the results from the __async request of AsyncStorage.getItem('api/credentials')__ (we end up setting it as an empty string no matter what).

This is causing JWT re-authorisation to fail and requests will never re-validate with a new token.

I'd suggest setting __storedCredsStr__ initially with the async call, then check its value later in the flow, that way it is never set to another value apart from what _should_ return from __api/credentials__.

If I have some time I'll go through and submit a pull request, just a heads up.

**Comment by mcnamee** [comment]
Hey @Jean-PierreGassin 
Definitely love to see a pull request to understand what you mean.

**Comment by typeslower** [comment]
Not sure if this is related but line 19 in redux/user/actions.js:
`if (!AppAPI.getToken) return resolve();`

Is this supposed to keep the user logged in from the stored token?

Hence LaunchView.js will skip the Auth screen. Was wondering if you could help me because when I check the promise I get:
![image](https://cloud.githubusercontent.com/assets/2566674/26278311/6fae37c4-3d65-11e7-9674-763eb49ff265.png)

However since it's Async I get this when I inspect the object:
![image](https://cloud.githubusercontent.com/assets/2566674/26278316/83399ad6-3d65-11e7-8302-a5efa831cf92.png)

Am I doing something wrong?

**Comment by mcnamee** [comment]
This project is now making use of Firebase (and the Firebase JS SDK).
So I'll close this one off
