### ISSUE TITLE
[Android] Can't find variable symbol

### ISSUE THREAD

**Issue by cstd** [mcnamee/react-native-starter-app#76]
It shows this error when i run on android device.

**Comment by rajawat24** [comment]
Getting same error, following attached error screen
![screenshot_1494423333](https://cloud.githubusercontent.com/assets/7202689/25942271/0c01dcc4-365a-11e7-87b2-707991463bd8.png)

**Comment by thi4go** [comment]
Same error here.

**Comment by barron9** [comment]
same

**Comment by cyberid41** [comment]
Hello, I am experiencing the same thing. However when I try to enable Remote JS Debugging apps running normally

**Comment by mcnamee** [comment]
Hey guys,
Looks like a dependency issue (with the striptags package). I've removed it and it runs on Android now.

I'll leave this open for a few more days, so give it a test and let me know if the issue persists for you.

**Comment by swanie21** [comment]
Hi Guys, 
I found a solution to this since I was receiving the same issue. The ES6 Symbol variable can't be found, so I installed the [es6-symbol dependency](https://www.npmjs.com/package/es6-symbol) `npm install es6-symbol`. Then I declared the variable `const Symbol = require('es6-symbol')` in the `striptags.js` file.

![striptags](https://user-images.githubusercontent.com/17103622/28680845-cadc2c30-72b4-11e7-9e5a-b349d487d132.png)
