### ISSUE TITLE
Question - Swipe left to close drawer and code-push installation

### ISSUE THREAD

**Issue by openqubit** [mcnamee/react-native-starter-app#85]
I want to create two features 

1. Swipe left to close an open drawer
2. Use code-push to keep my app up to date

Regarding 1 above, is this something you plan to implement in future and in 2, code-push wont work in react-native 0.42.x so has anyone upgraded react native without breaking anything?.

Thanks.

**Comment by mcnamee** [comment]
Hi @openqubit 
You should be able to implement 1. fairly easily - just follow the API from the [side menu repo](https://github.com/react-native-community/react-native-side-menu). I've disabled gestures because I wasn't happy with the UX when it was enabled (specifically that you couldn't swipe back on iOS anymore - instead it would open the menu).

I've used Code Push - however not with RN0.42+ yet.
