### ISSUE TITLE
Build failed when upgrading react native

### ISSUE THREAD

**Issue by hieuxit** [mcnamee/react-native-starter-app#95]
1. I'm using react-native-git-upgrade to upgrade to latest react native version 0.46.4
2. I try to re-run app but got error 
error: bundling failed: "TransformError: .../node_modules/react/index.js Cannot find module 'react-native/packager/rn-cli.config' (While processing preset: \".../node_modules/react-native-dotenv/index.js\")"

Do you have any suggestion or document of how to upgrading react native?
Any help would be appreciated.

**Comment by mcnamee** [comment]
Hi @hieuxit 
I'm generally slow to update to the latest RN version, because of issues like this. Unfortunately, we need to wait until all dependencies are also compatible with the latest version.

You issue might be specifically related to the `react-native-dotenv` - you could start by updating or removing that dependency (plus any references to it), if upgrading to the latest RN is a requirement.

**Comment by hieuxit** [comment]
@mcnamee Okie thank for your response. I hope you will update new RN version, because FlatList and SectionList is updating, and we should use this instead of ListView.
