### ISSUE TITLE
unable to start the app

### ISSUE THREAD

**Issue by nosizejosh** [mcnamee/react-native-starter-app#96]
Getting an error related to react-native-device-info.

...React Native\Starters\mcnamee_starter\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.2\res\drawable\common_google_signin_btn_text_light_normal.xml:5:30-65 : No resource found that matches the given name (at 'src' with value '@drawable/googleg_standard_color_18').

ruining on windows 10. Tried deleting the node modules folder, reinstalled twice and still no joy. @mcnamee any idea why this? or how to solve it?

**Comment by nosizejosh** [comment]
I have just read through [this ](https://github.com/mcnamee/react-native-starter-app/issues/88) and it seems to point to the android emulator, but i was attempting to run it on a device. Now sure why this should be a challenge though.

**Comment by mcnamee** [comment]
Hi @nosizejosh 
That issue was discussing the SDK's required. When it compiles (whether that's for emulator or physical device), both RN as well as various NPM modules require the Android SDKs.

Similar to the issue you've referenced, it might be that the NPM module you're having issues with `react-native-device-info`, requires an SDK that you don't have installed.

Try the solution from [this one](https://github.com/mcnamee/react-native-starter-app/issues/88) and let us know if it worked for you

**Comment by nosizejosh** [comment]
@mcnamee  I have tried that, it didn't work, tried to remove all instances of react-native-device-info that didn't work either. I have spend the last three days trying to run the starter app for the first time, still no joy. In fact i actually have sdk versions 23-25 all installed yet i cannot get this to start.

**Comment by nosizejosh** [comment]
after several tries, here is the latest error
`Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\oajos_000\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe'' finished with non-zero exit value 1`

**Comment by voukeng** [comment]
I have the same error. Please for help

**Comment by mcnamee** [comment]
This issue is related to your machine not locating the required Android SDK (either because it's not installed, or just cached without it).

Please ensure you have the exact versions of the SDK Platform + SDK Tools > Build Tools.
And you could also try the suggestion [over here](https://stackoverflow.com/questions/32873281/how-to-fix-23-0-1-aapt-exe-finished-with-non-zero-exit-value-1) RE: cleaning the project.
